spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672
  application:
    name: warehouseService

sensor:
  temperature:
    threshold: 35.0
  humidity:
    threshold: 50.0

logging:
  level:
    org:
      springframework:
        amqp: INFO