server:
  port: 8081
spring:
  application:
    name: warehouseMonitor
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

sensor:
  temperature:
    threshold: 35.0
  humidity:
    threshold: 50.0

temperature:
    data:
      queue: temperature.data.queue

humidity:
  data:
    queue: humidity.data.queue

logging:
  level:
    org:
      springframework:
        amqp: INFO